apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: producer
          image: load-kafka-project/producer-1
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"  # Kafka servisini Kubernetes içinden referans alıyoruz

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: consumer
          image: load-kafka-project/consumer-1
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"  # Kafka servisini Kubernetes içinden referans alıyoruz

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka

